In [1]:
import geopandas as gpd

In [3]:
df = gpd.read_file('data/Statewide_parcels_SHP/L3_TAXPAR_POLY_ASSESS.shp')

In [4]:
df.columns

Index(['MAP_PAR_ID', 'LOC_ID', 'POLY_TYPE', 'MAP_NO', 'SOURCE', 'PLAN_ID',
       'LAST_EDIT', 'BND_CHK', 'NO_MATCH', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHER_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE', 'USE_CODE', 'SITE_ADDR', 'ADDR_NUM', 'FULL_STR', 'LOCATION',
       'CITY', 'ZIP', 'OWNER1', 'OWN_ADDR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING', 'YEAR_BUILT',
       'BLD_AREA', 'UNITS', 'RES_AREA', 'STYLE', 'NUM_ROOMS', 'LOT_UNITS',
       'STORIES', 'SHAPE_AREA', 'SHAPE_LEN', 'geometry'],
      dtype='object')

In [5]:
df_concord = df.loc[df.TOWN_ID == 67]

In [6]:
df_concord

,MAP_PAR_ID,LOC_ID,POLY_TYPE,MAP_NO,SOURCE,PLAN_ID,LAST_EDIT,BND_CHK,NO_MATCH,TOWN_ID,...,BLD_AREA,UNITS,RES_AREA,STYLE,NUM_ROOMS,LOT_UNITS,STORIES,SHAPE_AREA,SHAPE_LEN,geometry
1262,2107,F_682887_2992644,FEE,9D,ASSESS,None,20110504,None,N,67,...,6030,0,2946,Colonial,8,Acres,2,1999.827365,196.230270,"POLYGON ((208165.082 912174.498, 208184.455 91..."
1353,2986-1,F_681563_2980927,FEE,14C,ASSESS,None,20110504,None,N,67,...,0,0,0,Vacant,0,Acres,0,1305.132182,197.731517,"POLYGON ((207778.843 908579.375, 207774.937 90..."
1527,1863,F_688344_2994292,FEE,8E,ASSESS,None,20110504,None,N,67,...,3079,0,1436,Ranch,7,Acres,1,2411.197838,204.520881,"POLYGON ((209844.934 912669.266, 209832.245 91..."
2543,2497,F_683094_2989244,FEE,10D,ASSESS,None,20110504,None,N,67,...,3833,0,1827,Old Style,8,Acres,1.75,433.043921,84.136203,"POLYGON ((208219.279 911122.479, 208219.739 91..."
2551,1101,F_701532_2996352,FEE,7I,ASSESS,None,20110504,None,N,67,...,3140,0,2060,Colonial,0,Acres,2,1905.903819,183.758876,"POLYGON ((213850.202 913264.313, 213833.115 91..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2408836,1985-31,F_686900_2999244,FEE,6E,ASSESS,None,20110504,None,N,67,...,5986,0,1876,Rsd Rnch/Splt Lvl,9,Acres,1,5274.319078,299.913278,"POLYGON ((209417.223 914185.954, 209389.392 91..."
2408837,1934,F_685600_2995674,FEE,7D,ASSESS,None,20110504,None,N,67,...,2033,0,1101,Old Style,6,Acres,1.75,1046.297060,138.054946,"POLYGON ((208989.376 913064.516, 208980.729 91..."
2408941,1999-2,F_683009_2996780,FEE,7D,ASSESS,None,20110504,None,N,67,...,0,0,0,Vacant,0,Acres,0,141562.068721,1969.907935,"POLYGON ((208213.603 913594.564, 208474.836 91..."
2408942,1044,F_703820_2996764,FEE,7J,ASSESS,None,20110504,None,N,67,...,3936,0,1120,Cape Cod,5,Acres,1.5,2336.228540,198.916146,"POLYGON ((214560.715 913414.656, 214557.969 91..."
2409097,2822,F_682979_2988084,FEE,11D,ASSESS,None,20110504,None,N,67,...,6066,0,3454,Colonial,0,Acres,2,1929.948201,189.170171,"POLYGON ((208207.257 910789.103, 208170.590 91..."

In [7]:
df_concord.FULL_STR.unique()

array(['POND ST', 'OLD PICKARD RD', 'COBURN HILL RD', 'SHIRLEY ST',
       'ARROWHEAD RD', 'PINE HILL LN', 'SUDBURY RD', 'ROLLINGWOOD LN',
       'CENTRAL ST', 'STONE ROOT LN', 'LOWELL RD', 'COTTAGE ST', 'ASH ST',
       'INDIAN SPRING RD', 'MUSKETAQUID RD', 'FAIRHAVEN RD', 'MAIN ST',
       'ARENA TER', 'HARRINGTON AVE', 'BLACK DUCK RD', 'WOODLAND RD',
       'PARK LN', 'HAWTHORNE LN', 'SPRING RD', 'NASHAWTUC RD',
       'HAYWARD MILL RD', 'MARTHAS POINT RD', 'HUBBARD ST',
       'CAMBRIDGE TPKE', 'BEDFORD ST', 'NASHOBA RD', 'PILGRIM RD',
       'ALDEN RD', 'WALDEN ST', 'POPE RD', 'LANG ST', 'PLAINFIELD RD',
       'DANA RD', 'RIVERDALE RD', 'ASSABET AVE', 'RANGE RD',
       'LAWS BROOK RD', 'BLUE JAY DR', 'WESTFORD RD', 'THOREAU ST',
       'PETER SPRING RD', 'MONUMENT ST', 'DOVER ST', 'BRUCE RD',
       'SEYMOUR ST', 'OAK HILL CIR', 'CREST ST', 'SOUTHFIELD RD',
       'GROVE ST', 'SPENCER BROOK RD', 'FITCHBURG TPKE', 'BELKNAP ST',
       'OLD MARLBORO RD', 'BRIDGECOURT LN', 'COMMONWEALTH AVE',
       'OLD STOW RD', 'JENNIE DUGAN RD', 'BAKER AVE',
       'OLD RD TO 9 ACRE COR', 'BIRCH DR', 'MILDRED CIR', 'WRIGHT RD',
       'HIGHLAND ST', 'LEDGE ROCK RD', 'LEXINGTON RD', 'SHADYSIDE AVE',
       'BAKER AVENUE EXT', 'HAYES RD', 'BOLTON ST', 'SOUTHFIELD CIR',
       'BARNES HILL RD', 'OLD MILL RD', 'HEATHS BRIDGE RD',
       'HIGH PINE CIR', 'QUAIL RUN DR', 'MINUTEMAN DR', 'COMMERFORD RD',
       'RIDGEWOOD RD', 'BORDER RD', 'HILDRETH LN', 'SOUTH ST',
       'WILSON RD', 'REVOLUTIONARY RD', 'TANGLEWOOD DR',
       'CROWELL FARM RD', 'ANNURSNAC HILL RD', 'BARTLETT HILL RD',
       'FULLER LN', 'CATERINA HTS', 'HUNTERS RIDGE RD', 'RAYMOND RD',
       'PHILIP FARM RD', 'SANDY POND RD', 'INDEPENDENCE RD', 'ADAMS RD',
       'SIMON WILLARD LN', 'VIRGINIA RD', 'BUCKMASTER DR', 'EDGEWOOD RD',
       'COTTAGE LN', 'WHIPPOORWILL LN', 'LAPHAM RD', 'OLD BEDFORD RD',
       'DUNBAR WAY', 'DERBY ST', 'NORTH BRANCH RD', 'DOMINO DR',
       'SIMON WILLARD RD', 'BYPASS RD', 'PARTRIDGE LN',
       'BARRETTS MILL RD', 'NANCY RD', 'MUNROE PL', 'WESTVALE DR',
       'ESTABROOK RD', 'WHITTEMORE ST', 'GARFIELD RD',
       'TARBELL SPRING RD', 'MACMILLAN DR', 'BEDFORD CT', 'LEE DR',
       'HILLCREST RD', 'ELSINORE ST', 'LANES END', 'ALLEN FARM LN',
       'CONANT ST', 'POWDER MILL RD', 'PRAIRIE ST', 'BEHARRELL ST',
       'NIMROD DR', 'EDMONDS RD', 'THE VALLEY RD', 'SHORE DR',
       'HILLSIDE AVE', 'KENNEY LN', 'SARAH WAY', 'MUSTERFIELD RD',
       'ANSON RD', 'COLLEGE RD', 'MARTIN RD', 'STOW ST',
       'JONAS BROWN CIR', 'STRAWBERRY HILL RD', 'WINTHROP ST',
       'CRABTREE RD', 'RIVERSIDE AV', 'CONCORD TPKE', 'BLUEBERRY LN',
       'BUTTRICKS HILL RD', 'SAW MILL RD', 'BUTTERNUT CIR',
       'FAIRHAVEN HILL RD', 'WHITS END RD', 'GRANITE POST RD',
       'PEABODY CT', 'INGHAM LN', 'JUNIPER CIR', 'UPLAND RD',
       'CHESTNUT ST', 'BROWN ST', 'AUTHORS RD', 'STACEY CIR',
       'MINISTERIAL DR', 'BALLS HILL RD', 'TEMPLE RD', 'ELM ST',
       'MONSEN RD', 'AUTUMN LN', 'PAUL REVERE RD', 'FARMERS CLIFF RD',
       'MACARTHUR RD', 'LORING RD', 'BLACK HORSE PL', 'DEER GRASS LN',
       'MINOT RD', 'OXBOW RD', 'SILVER HILL RD', 'HOLDEN WOOD RD',
       'PRESCOTT RD', 'LAUREL ST', 'HOSMER RD', 'SUMMIT ST',
       'WEDGEWOOD CMN', 'EMERSON RD', 'POTTER ST', 'NUT MEADOW XING',
       'PLEASANT ST', 'ROBINWOOD RD', 'DEACON HAYNES RD', 'EAST CIR',
       'DALTON RD', 'ISAAC DAVIS RD', 'BIGELOW RD', 'HEMLOCK ST',
       'AURORA LN', 'HILL ST', 'UNION ST', 'MERIAM RD', 'MCCALLAR LN',
       'WHEELER RD', 'MATTISON DR', 'CARR RD', 'WHITE AVE', 'CHANNING RD',
       'FINIGAN WAY', None, 'GARDEN RD', 'WILLOW ST', 'KING LN',
       'LINDSAY POND RD', 'BELKNAP CT', 'EATON ST', 'GRANT ST',
       'BYRON ST', 'THOREAU CT', 'BRISTERS HILL RD', 'WILLIAMS RD',
       'PETER BULKELEY RD', 'SHAGBARK RD', 'RIDGEWAY RD', 'MIDDLE ST',
       'BROOK TRAIL RD', 'DAMON ST', 'EVERETT ST', 'PHEASANT LN',
       'SORREL RD', 'ORCHARD RD', 'KEYES RD', 'OLD FARM RD',
       'INDIAN PIPE LN', 'BROOKS ST', 'DAVIS CT', 'BAYBERRY RD',
       'ATTAWAN RD', 'WINSLOW ST', 'DARTON ST', 'CRESS BROOK RD',
       'OAK RD', 'WOOD ST', 'STUDLEY CT', 'HUGH CARGILL RD', 'RIDGE RD',
       'DEVENS ST', 'CHASE RD', 'AYRSHIRE LN', 'WEST CIR', 'CHURCH ST',
       'LIBERTY ST', 'DAMONMILL LN', 'MONUMENT FARM RD', 'MANUEL DR',
       'HAYWARD MILL CIR', 'GREAT MEADOWS RD', 'KEUKA RD', 'FERN ST',
       'MAPLE ST', 'POND VIEW LN', 'RIVER ST', 'UNION TPKE',
       'OLD POWDER MILL RD', 'HIGH ST', 'WALDEN SQ', 'FRANCES ST',
       'KNOX TRAIL RD', 'ALFORD CIR', 'COOLIDGE RD', 'ADIN DR',
       'CAPTAIN MILES LN', 'DRUM HILL RD', 'SUNNYSIDE LN',
       'FOREST RIDGE RD', 'CRESCENT RD', 'GARRISON RD', 'LEWIS RD',
       'WALDEN TER', 'GREENFIELD LN', 'SIDNEY LN', 'WARNER ST', 'WEST ST',
       'POWERS RD', 'BRADFORD ST', 'FIELDING ST', 'RIVERDALE CIR',
       'CONCORD GREENE', 'FLORIO DR', 'GIFFORD LN', 'MALLARD DR',
       'ALCOTT RD', 'PINE ST', 'VALLEY ST', 'MONUMENT SQ',
       'WESTVALE MEADOW', 'GARLAND RD', 'INDEPENDENCE CT', 'WATER ST',
       'CRANEFIELD RD', 'RIPLEY HILL RD', 'SEVEN STAR LN',
       'OFF HARRINGTON AV', 'WRIGHT FARM', 'MILLRUN LN', 'PAUL ST',
       'MITCHELL RD', 'SWEET BIRCH LN', 'ELM BROOK LN', 'RED COAT LN',
       'OLD BRIDGE RD', 'WOLF PINE WAY', 'TURNING MILL RD', 'HEYWOOD ST',
       'BARTKUS FARM', 'WESTGATE PARK', 'MACONE FARM LN', 'BRIGHAM WOODS',
       'FLINT RD', 'WINDMILL HILL RD', 'TWO ROD RD', 'COPPERMINE RD',
       'SQUAW SACHEM TRL', 'LONGFELLOW RD', 'HOLDEN LN', 'MAPLEWOOD CIR',
       'COURT LN', 'WALNUT ST', 'BLUE HERON WAY', 'TRACY ST',
       'BARTONS WAY', 'STAFFORDSHIRE LN', 'MAGNOLIA ST', 'JUNCTION SQ',
       'CENTER VILLAGE DR', 'SHAW FARM RD', 'GRANBY ST', 'FOX LN',
       'BRONSON WAY', 'BOW ST', 'WAYSIDE RD', 'SOUTH MEADOW RDG',
       'WILLARD CMN', 'CONCORD XING', 'CEDAR WAY', 'DRAKE PARK RD',
       'PRESTON ST', 'MAPLE CT', 'CRANBERRY LN', 'POND LN', 'THORNTON LN',
       'ACADEMY LN', 'RIVER MEADOW', 'LOVE LN', 'BLACK BIRCH LN',
       'EMERSON HOSPITAL', 'HAYWARD CT'], dtype=object)

In [8]:
df_concord.to_csv('data/concord_parcel_df.csv')

In [14]:
df_concord.loc[df.FULL_STR=='ELM ST']

,MAP_PAR_ID,LOC_ID,POLY_TYPE,MAP_NO,SOURCE,PLAN_ID,LAST_EDIT,BND_CHK,NO_MATCH,TOWN_ID,...,BLD_AREA,UNITS,RES_AREA,STYLE,NUM_ROOMS,LOT_UNITS,STORIES,SHAPE_AREA,SHAPE_LEN,geometry
118596,1832,F_689189_2993713,FEE,8F,ASSESS,None,20110504,None,N,67,...,6458,0,3193,Colonial,0,Acres,2,4619.820736,280.146537,"POLYGON ((210103.786 912518.923, 210076.907 91..."
215774,3799,F_688383_2993692,FEE,8E,ASSESS,None,20110504,None,N,67,...,3704,0,1344,Ranch,6,Acres,1,1871.551427,174.327746,"POLYGON ((209846.820 912495.604, 209828.912 91..."
275643,1769-3,F_692055_2992774,FEE,9F,ASSESS,None,20110504,None,N,67,...,0,0,0,Vacant,0,Acres,0,9382.359792,465.327268,"POLYGON ((211019.311 912211.836, 211018.071 91..."
313909,1797-1,F_689845_2993514,FEE,8F,ASSESS,None,20110504,None,N,67,...,10235,0,5627,Custom,16,Acres,2,3885.864805,272.519502,"POLYGON ((210302.210 912460.477, 210290.530 91..."
390926,1769-1,F_691789_2992768,FEE,9F,ASSESS,None,20110504,None,N,67,...,6687,0,2964,Old Style,8,Acres,1.75,3842.371061,269.057118,"POLYGON ((210866.624 912216.259, 210908.534 91..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2218138,1846,F_688418_2993929,FEE,8E,ASSESS,None,20110504,None,N,67,...,5289,0,2336,Ranch,8,Acres,1,1735.145354,176.392642,"POLYGON ((209853.354 912575.540, 209833.961 91..."
2298767,1899-1,F_686035_2994801,FEE,8E,ASSESS,None,20110504,None,N,67,...,5088,0,4888,Restaurant,0,Acres,2,7941.856170,366.464481,"POLYGON ((209122.557 912757.353, 209047.938 91..."
2314819,1843,F_688702_2993832,FEE,8E,ASSESS,None,20110504,None,N,67,...,5804,0,2330,Rsd Rnch/Splt Lvl,9,Acres,2,1886.938123,183.913606,"POLYGON ((209941.308 912545.742, 209921.744 91..."
2406433,1917,F_684722_2995276,FEE,8D,ASSESS,None,20110504,None,N,67,...,12870,0,12870,Other State,0,Acres,1,11625.537495,456.276394,"POLYGON ((208727.419 912884.912, 208687.872 91..."
2408941,1999-2,F_683009_2996780,FEE,7D,ASSESS,None,20110504,None,N,67,...,0,0,0,Vacant,0,Acres,0,141562.068721,1969.907935,"POLYGON ((208213.603 913594.564, 208474.836 91..."